# Generated by Django 3.1.12 on 2025-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_backup', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='songbackup',
            name='is_favourite',
        ),
    ]
