# Generated by Django 3.1.12 on 2025-04-03 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_auto_20250403_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupstatus',
            name='last_backup',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='songbackup',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songbackup',
            name='channelName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='songbackup',
            name='currentTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='songbackup',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='songbackup',
            name='savedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='songbackup',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='songbackup',
            name='videoId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
