# Generated by Django 3.1.12 on 2025-04-03 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proxyapp', '0002_auto_20250403_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupstatus',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='backupstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='backupstatus',
            name='last_backup',
        ),
        migrations.AddField(
            model_name='backupstatus',
            name='backup_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupstatus',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupstatus',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backupstatus',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupstatus',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupstatus',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backupstatus',
            name='status',
            field=models.CharField(default='running', max_length=20),
        ),
        migrations.AddField(
            model_name='backupstatus',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
    ]
